# Circle CI configuration file

version: 2.1

jobs:
  build: # Name of the job
    macos:  # Specify the OS
      xcode: "14.2.0" # Specify the Xcode version
    steps: # Steps to run
      - checkout # Checkout the code
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies


      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Build
      - run:
          name: build
          command: ./gradlew clean assemble
