# Circle CI configuration file

version: 2.1  # CircleCI config version

jobs:  # Define the jobs section
  build-and-test:  # Define a job named "build"
    macos:
      xcode: 14.0.1
    working_directory: ~/project/LearnFlow  # Set the working directory to the root of the project
    steps: 
      - checkout  # Check out the code from the repository

      # Task : Clear Gradle cache
      - run:
          name: Clear Gradle Cache
          command: ./LearnFlow/gradlew cleanBuildCache

      # Clear CircleCI cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # Add more cache keys for other dependencies if needed
          name: Restore Gradle Dependencies

      # Task : Download and install dependencies
      - run:
          name: Download Dependencies
          command: ./LearnFlow/gradlew androidDependencies

      # Task : Build the project
      - run:
          name: Build
          command: ./LearnFlow/gradlew clean assemble

      # Task : Run tests
      - run:
          name: Run Tests
          command: ./LearnFlow/gradlew test

      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-dependencies-{{ checksum "build.gradle" }}

# Define a workflow named "simple-workflow" that includes the "build-and-test" job
workflows:
  simple-workflow:
    jobs:
      - build-and-test