# Circle CI configuration file

version: 2.1  # CircleCI config version

jobs:  # Define the jobs section
  build:  # Define a job named "build"
    steps: 
      - checkout  # Check out the code from the repository

      # Task : Download and install dependencies
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      # Task : Build the project
      - run:
          name: Build
          command: ./gradlew clean assemble

      # Task : Run tests
      - run:
          name: Run Tests
          command: ./gradlew test
