# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Generate  screenshots"
  lane :screenshots do
    build
    capture_android_screenshots
  end

  desc "Increment version"
   lane :increment_version do
   increment_version_code(
         gradle_file_path: "./app/build.gradle",
   )
   end

   desc "Build"
   lane :build do
     gradle(
        task: "assemble",
        flavor: "dev",
        build_type: "Release"
      )
    end
end
